language: python
python:
  - "2.7"

# setup environment variables
env: PYTHONPATH=$TRAVIS_BUILD_DIR/..:$PYTHONPATH

before_install:
  - sudo chown travis /var/log

# command to install dependencies
install:
  - make deps

# give permissions to write to log file
before_script:
  - sudo mkdir $TRAVIS_BUILD_DIR/logs/
  - sudo chown travis $TRAVIS_BUILD_DIR/logs/

# run tests
script:
  - make test


notifications:
  email:
    recipients:
      - developers@growthintel.com

  slack:
    rooms:
      secure: "TlcA3vO995ZtVQiW4Rto1sLHZEZT6a7gzJyJk8dTxJEj0mNGQANgqdtcXZOSmITKdXRzc0kHkHJ7Z3Que2tUhCOxLdLwX7liLm1PGjrCs1QDtt90YWBnarPLpgneUO/2HQ0SgBDouJZm9S43dorWNcIXqUiz8ytOeAG2QusE2wZN/aFNdXN0e5qMeZlbpOQoOEfguNDolK+81HwZVCT+UHwLqLK1md4nEkv0Ky/HLhnKeum0Xt2H8DrHDPwnIZZxD7uytXxhmIQkHK22bcHRQX2fWWPHVK6hzU7QvMGnRf8SO9qrUNT0+JS+dwgyAp34UygqRw2nzIcWqKjEfK7OGIhrC6DI0gx0v0DZofede8u8qrLXpjH9yDCDlWK5zxm3/l+m2YuOLA5OmAP+gI3uwDXrMLPD+s/Bm3/wNcNI7gDfx0SYS+r23zwbHZOtX9ze/AwivShg8U/e6AC77J7vtr9wABEkML5qzeQWTTVsvqsDFvw7g25FqTvIBZJGZwTUaUVUIeHIVpjaskEywzrI9PMachlEkHo2UgydvAkMIgcDau6Y5OThE76m7giwmvVNUFpgrpTyVO91euU43rcpS/1ApjRxOju81KoGZRqrnYq+J8WhvNusj5hjKaVRRjOW6aMNXcyZLGk9Ma9w8Xl2ad9sx2N5D7eZjJuE6fO3Dg8="