language: python
python:
- '2.7'
env: PYTHONPATH=$TRAVIS_BUILD_DIR/..:$PYTHONPATH
before_install:
- sudo chown travis /var/log
install:
- make deps
before_script:
- sudo mkdir $TRAVIS_BUILD_DIR/logs/
- sudo chown travis $TRAVIS_BUILD_DIR/logs/
script:
- make test
notifications:
  email:
    recipients:
    - developers@growthintel.com
  slack:
    rooms:
      secure: "kb81nj9Wjv69jRCR9muWuUldxACnJAue+7afSY7DK7RYn6fOmeyKNNlY5drjraKY8lqHh+mSjZctNPjQSNw3n1BdYoUXrMbfDL7rsORxGJuOKDFnW879p88rtFDOApIedA9fl4rYL2mIxplUpNZi6/aTJtCaB/ZkJMu0O+wGgqXlI0Gp6pPolRrVhqKSXmWS3s4y6mrpJFrGyrwdxdUgp801j1YCGSh6YPH6KJhZYIMhXmHZSxNSNaxjOEA5iqFkvGpzzhjn8ofmIRhtUE55RiZu7CdAT9oizXojFK5ofALgPuK1+UGU6sutZNHzeURwkQqBERMFGyAk79n56nKBzUZqcAPxNg/l1yz6axVBgdBMHV7LuN0lFha04D17DILm/83wnEIVK+xNGEcYh7QkCppVUWo274anKWn97rtaMy/sPITs/IxetkD29TJnDXdDm8wufdOXWQYOXJT8qRKLl1pCcgy53yx5SHANrdPemKqzskk1kqDo5LjcLQiUnDFC9FlaeeYArqlEo0R0SjdT1hK9YJLiuGJjvhd2maOUBQqxNYKnH5z19MMGHOT254wbcXHOFKhSov/U865yi6R1HKtWjjAo3aLF/nNoKpO06oXTdOgfdSIavG9knjeDOK+WVf50QJbDiTz7M1srsaZ/U34c/ndf+Bi3jAKxoqcb9R0="
