language: python
python:
  - '2.7'
env: PYTHONPATH=$TRAVIS_BUILD_DIR/..:$PYTHONPATH
before_install:
  - sudo chown travis /var/log
install:
  - make deps
before_script:
  - sudo mkdir $TRAVIS_BUILD_DIR/logs/
  - sudo chown travis $TRAVIS_BUILD_DIR/logs/
script:
  - make test
notifications:
  email:
    recipients:
    - developers@growthintel.com

  slack:
    rooms:
      secure: "FnyOmQiFhUWjosCAh6eQN54uIqjzipy5Oydbdyh/OxH9Mf3eswOT2GHdOwhA4pYn39OR8ZEyGgrKa2J08wchpPisxFCC5+3+a+ki/wN1lI3H1A7Yr5qLY5ZSL9JPEM7dgkfeh0N510PqU5dOMWuZnOzpSieE5tAVqbP6bHS/vD07ryLbNbTRlwtZDSun3+SbMAJmPgqX/9rAVcGf2MfQfU6peOD/qBCWfvJtGS5iJPIcCELP840TZSK94+sCuctiQ/4sziZ9I7bB94OCsBqJDvn5bqYakQL4bt5+jh2LAwVoYUHeQozqJ7lCiY3LeZLurQz6Ny5dspzntHY9+JS0GW8bX3EWK7zIKyUW7Agnd4H1rB36PX2XwD7BVZRKk6CBrAU2cZtJbRN4t/0NyySb+t3unoHyJM43HoGEBHxNOvTcwfI/XqaRDanDKl3XmtF0V63LtbdOvWrxkpPlbdu1ly04oo1CCj3hStE3QxKMkTTWLELn/pI8HePG6BF8udozPdUXv1DbIb0UhyJu/AVoRewFEVNQhRwcFfGEEn+bSymBzTMU/hu6KM0M+bsgf8gugNsCKnSvvHSEmr+kJFVnDEt2uXlIDxVAydSES2xwJbsLMQItv4RNzQErbAPrzsuv+xnjVBndA4c3oRzDPTBOEy96OzF5Bqe/+vs0rIPFBjI="
