language: python
python:
- '2.7'
env: PYTHONPATH=$TRAVIS_BUILD_DIR/..:$PYTHONPATH
before_install:
- sudo chown travis /var/log
install:
- make deps
before_script:
- sudo mkdir $TRAVIS_BUILD_DIR/logs/
- sudo chown travis $TRAVIS_BUILD_DIR/logs/
script:
- make test
notifications:
  email:
    recipients:
    - developers@growthintel.com
  slack:
    secure: "FaMnH6SMxYa9s4l83K7y9LvIO2xjIRwGw0qcHSbnKPJSGDjyn1lqZX8ZcbfGhQv+j2+mqcjEW8gL7YAl/zVN5Yl/vv+4O6mvzdlyUrS7RRzRGwbhFeroWTJp269kC53PG+c20OXymroG89Oz8OCvwm9aKY9wdgvnbJTKj5c5PxmnR/7LT1kAWK/LFqmMurLAG2zGtfIvH6zi/X519ARdYSE4TCyLc6sZRoVJpC50TT0/wMgXTCzCU7SPoEM32CkvjaWJ/bdHy2a92YvLAUo6eP722P61/TR2SRA3EXffQmdfZ6pZqitR8kYbgw7fFoMzA2Fccbr7OlBYMOfZt1ocQoYECkycixQ79/8oSILBzLxYvwsi+gYB4/m4pg8aW5wIPKM//efgPn1wumwL3KjAQvXULRxmCsmJafRm2dMHWJKKwp7LwFes3il2sgpo6g0QMRZvtcbjffhGJGr1/BlkL4lVAEPcrbr1XAJd9C6Y1yJyAk0O1Wbmf6v0PnX3yz1NphZZMCQq0cyLpG/sFK82MuUV4C1Zh3iZurJgg2IU0ZkFa2HEJB727Y8leC9kHRolLa+kmSehZFepN22n4+WPySM58vrlDm3aImxhdoGL7TPpbBzWQhBy1jJyOr3JKuY4gWpEuIWPwbCshVfKce8GqxMpUU2woLXdE8SaUp2p/1U="
